### PR TITLE
Feature/correct old links

### PR DESCRIPTION
**Pull request by abhijitkane**
All site.pm.gs links should point to go.postman.co. (still waiting for clarity on the /integrations links)
Removed all target=blank till we're able to do it in Gatsby or something

### CODE REVIEW

**Comment by abhijitkane** [comment]
@wsfuller The remaining ones are HTML-only (not in the templating language). Can you remove them if they need to be removed too?

**Comment by wsfuller** [comment]
Apologies I clicked the wrong commit

**Comment by wsfuller** [comment]
LGTM

**Comment by abhijitkane** [comment]
Merging to remove `target=blank`s

**Pull request merged**
