### PR TITLE
Delete hipchat and add redirect to main page

### PR DESCRIPTION
**Pull request by jerry-li-dev**
- Deleted hipchat integrations page
- Redirect to main integrations page

### CODE REVIEW

**Comment by jerry-li-dev** [comment]
HipChat integration is no longer supported. We need to remove this page and redirect to the main integrations page.

**Comment by tristandenyer** [comment]
@jerry-li-dev There is a link left behind on `changelog-and-restoring-collections.md` to old hipchat page that needs to be removed. And there are 3 old redirects still pointing to old hipchat page that need to be updated to main page. Search for `"to": "/docs/integrations/available-integrations/hipchat/"` in redirects file.

**Review by tristandenyer — CHANGES_REQUESTED** [review]
see comment

**Review by tristandenyer — APPROVED** [review]
LGTM

**Pull request merged**
