### PR TITLE
Updated certificate installation commands for Linux

### PR DESCRIPTION
**Pull request by abhishekc23**
Updated the commands for the installation of certificates in for the Linux distributions

### CODE REVIEW

**Review by jerry-li-dev — APPROVED** [review]

**Comment by shivanimaheshwari10** [comment]
@jerry-li-dev can you get this PR merged?

**Comment by jerry-li-dev** [comment]
PR just merged. Need someone with higher access to merge to prod.

**Comment by jerry-li-dev** [comment]
@sowmyaraj92 do you have access level to merge to prod?

**Comment by sowmyaraj92** [comment]
> @sowmyaraj92 do you have access level to merge to prod?

@jerry-li-dev Yes, I have. Raising a PR to merge the changes to prod. 👍

**Pull request merged**
