### PR TITLE
Small Spelling Fix

### PR DESCRIPTION
**Pull request by irishgordo**
- adjusted the spelling of "worksapce" to read as "workspace"
- adjusted "Github" to read as "GitHub"

Resolves: fix/small-spelling-fix

### CODE REVIEW

**Comment by irishgordo** [comment]
Hey there!

Love Postman so so so much!
Just happened to find a few spelling edits I thought it might be worth doing a little PR for.

Y'all are stellar!
Let me know if there is anything else I can help out on with this PR :smiley:

**Comment by sowmyaraj92** [comment]
> Hey there!
> 
> I love Postman _so so so much_!!
> Just recently happened to find a few spelling edits I thought it might be worth doing a little PR for.
> 
> Y'all are stellar!
> Let me know if there is anything else I can help out on with this PR 😃

@irishgordo Thank you so much for pointing it out Mike! :)

**Review by sowmyaraj92 — APPROVED** [review]
Looks good to me! 🎉

**Comment by irishgordo** [comment]
Glad I could help @sowmyaraj92 ! :)

**Pull request merged**
