### PR TITLE
Console and resizable panes

### PR DESCRIPTION
**Pull request by SueSmith**
**7.28 release**

Mainly image updates with a little text adjustment @coditva if there's anything else you think should be highlighted please give me a shout!

### CODE REVIEW

**Comment by coditva** [comment]
@SueSmith These changes look amazing! 💯 

One thing that we're introducing with this release is the **collapsing** of panes wherein you can hide panes which you don't need to declutter your workspace. You can collapse a pane either by dragging it or clicking on the collapse toggle buttons (the little arrows in the pane header). You can also open a collapsed pane by clicking on the tab e.g. if you've collapsed the request editor pane, you can just click on "headers" tab to open the pane and start working on the headers.



image
The arrow in the response pane header at the right will collapse this pane

I'm not sure where we can put it in the docs but you're the expert here 😁

**Comment by coditva** [comment]
And another minor issue/non-issue is that we have the app name as "Postman Stage" in first two screenshots. Maybe we can wait for production release or crop it out if it's an issue?

**Comment by SueSmith** [comment]
@coditva thanks for checking this so fast! 🙌 I'll add a bit on collapsing (had totally missed that 🤦‍♀️) and yeah for sure re stage pics, they'll do for publishing on release but I'll aim to get prod versions dropped in as soon after as I can 👍

**Comment by SueSmith** [comment]
@coditva mentioned collapsing and added a gif to better show both resizing and collapsing.. Should be good to go for Mon! 

resizing

**Comment by SueSmith** [comment]
@claireriley could you give this a once over for me, is mainly imgs..

**Pull request merged**
