### PR TITLE
Add docs for Super Admin feature

### PR DESCRIPTION
**Pull request by claireriley**
One additional screenshot to edit once UI is updated here: /docs/administration/team-settings/#understanding-roles-and-permissions, may be in a follow up PR if necessary.

### CODE REVIEW

**Review by ArjunSingh-PM — APPROVED** [review]
The changes look good. Thanks @claireriley

**Review by jkonrath-postman — APPROVED** [review]
LGTM

**Review by mark-anthony-postman — APPROVED** [review]
LGTM!

**Review by HeatherStenson — APPROVED** [review]
Looks good! 🍊

**Pull request merged**
