### PR TITLE
changed all links from learning.getpostman.com to learning.postman.com 

### PR DESCRIPTION
**Pull request by orama254**
Greetings team,

as requested by @ch264 on issue #2167  Kindly find the proposed changes to the repository

Issue #2167 :  change all links from learning.getpostman.com to learning.postman.com

### CODE REVIEW

**Comment by ch264** [comment]
@orama254 Thanks so much for contributing. This is great. There is one small change before merging your PR.

**Comment by orama254** [comment]
> @orama254 Thanks so much for contributing. This is great. There is one small change before merging your PR.

You are welcome @ch264 . Happy to contribute, I loved the flow of the contributing instructions as well.

**Comment by ch264** [comment]
@orama254  I was wondering when you could make the change so that we can merge your PR? Thanks

**Comment by orama254** [comment]
> @orama254 I was wondering when you could make the change so that we can merge your PR? Thanks

@ch264 I was waiting for further clarification of the small changes before I proceed, I was divided on whether to revert to previous changes or to wait for further clarification on the changes to be made

**Comment by ch264** [comment]
@orama254 sorry I thought I had commented on the file yesterday.

So the only change we need is in file .github/workflows/prod-deploy.yml

The line should be: 
`npm run build:prod && node_modules/s3-deploy/bin/s3-deploy './public/**' --cwd './public/' --bucket learning.getpostman.com --deleteRemoved --distId $DIST_ID --invalidate '/*'`


This is because we are not changing our bucket names just yet. Thanks so much for your help with this :)

**Comment by orama254** [comment]
@ch264 feel free to review the updated changes

**Comment by SueSmith** [comment]
Hi @orama254 just to let you know your changes have now been pushed to the live [Postman Learning Center site](https://learning.postman.com/) - thanks again! 🙌 🎉 🚀

**Comment by orama254** [comment]
Its an honor to contribute to one of my day to day tools. Looking out for more issues to contribute to
cheers @SueSmith

**Comment by SueSmith** [comment]
That would be much appreciated! 😊

**Pull request merged**
