### PR TITLE
Session faq link and Note

### PR DESCRIPTION
**Pull request by ArifPMan**
Hey, 

Can you please review and approve?

### CODE REVIEW

**Comment by loopDelicious** [comment]
@ArifPMan how do you get to this page? `v6/postman/environments_and_globals/sessions.md`

I don't see it in the sidebar navigation or search results.

**Comment by ArifPMan** [comment]
@loopDelicious this is again the issue we are facing after docs were migrated to LC. @tristandenyer I think this one also needs to be fixed.

**Comment by tristandenyer** [comment]
Looking into this.

**Comment by tristandenyer** [comment]
Update to left nav has been merged into Prod. "Sessions" is now showing in left nav. Please verify: https://learning.getpostman.com/docs/postman/environments_and_globals/sessions

**Pull request merged**
