### PR TITLE
Feature/presence

### PR DESCRIPTION
**Pull request by JJGothard**
The feature is due to be released on the 8th of March. Given the length of these reviews, and after discussing with @sankalp0o , I want to get that process underway now. Sankalp feels  it's fine if we're a couple days ahead of the release, should this PR go that way. @sankalp0o , give this a look, if you can.

### CODE REVIEW

**Comment by SueSmith** [comment]
@JJGothard this seems to have run in postman button stuff in it as well as presence stuff - can you make sure it only includes the presence stuff before we review? Have a look at the files changed here on GitHub and you'll see what's included in the pr.. 🙂

**Comment by SueSmith** [comment]
Whenever you create a new branch it should be from `develop` branch, that might be what's gone wrong here..

**Comment by JJGothard** [comment]
I'll take a look @SueSmith , thanks for the heads up!

**Comment by JJGothard** [comment]
@sankalp0o , "seconds" is what I have in my notes from when I was testing, I wrote minutes by mistake. 😳Probably cos I'd just talked to you about minutes...

**Comment by JJGothard** [comment]
Closing this request. All necessary changes have been cherry picked onto a new branch.

**Pull request closed without merging**
