### PR TITLE
[TW-770] Assign users to roles via SCIM

### PR DESCRIPTION
**Pull request by MatthewPinsker-postman**
* Clarified that roles assigned to a group are also assigned to its group members.
* In the **Create group** and **Update group members** bullet points, updated/added links pointing to:
    * updating group roles
    * controlling additional group access/permission

### CODE REVIEW

**Review by jkonrath-postman — APPROVED** [review]
LGTM

**Review by mark-anthony-postman — APPROVED** [review]
Looks great! 🌟

**Comment by johnoffon** [comment]
Looks good!

**Comment by johnoffenhartzPM** [comment]
Looks good!

**Pull request merged**
