### PR TITLE
Fix #1982: Add tracking for EditDoc button

### LINKED ISSUE #1982: Add Google click event tracking to 'edit' button
**Good issue for a first time contributor, or anyone that is interested.**

We want to know if people are clicking on the new "Edit this doc" button, and which topic they are  doing it on.

We can do that following these instructions: https://www.northstudio.com/blog/how-set-event-tracking-google-analytics/

One change I want to make is to make the `label` part dynamic by pulling in the slug from `location` (in URL). This way, we not only get the dimension of total number of clicks, but we can also start to see which pages get the most clicks (a signal that there may be an issue in that page.)

### PR DESCRIPTION
**Pull request by giatuongtran9**
_Label: pathRoute (/Docs/postman/launching-Postman/installation-and-Updates)
_OutBoundLink component, initialize ReactGA with Google Analytics tracking code so GA will know which collector to push data to
_Create ReactGA Event with ```ReactGA.event({})```
_Replace ```<a> tag``` in ```EditDoc.jsx``` to ```<OutBoundLink> component``` to enable tracking

### CODE REVIEW

**Comment by giatuongtran9** [comment]
@ch264 sure, I will try to switch to gatsby-plugin-google-tagmanager

**Comment by ch264** [comment]
@giatuongtran9 that is awsome, thanks so much for digging into it.

**Comment by ch264** [comment]
@giatuongtran9 how is it going? just checking in 😸

**Comment by giatuongtran9** [comment]
@ch264 I am afraid that I cannot switch to google tagmanager, even with the [gatsby-plugin-google-tagmanager doc](https://www.gatsbyjs.org/packages/gatsby-plugin-google-tagmanager/). I can try doing it with [gatsby-plugin-google-analytic](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/) but I have no idea how to do it with google tag manager. I'm sorry to delay your work.

**Comment by ch264** [comment]
@giatuongtran9 We very much appreciate your effort. We have found another solution so I will close this ticket. Happy holidays.

**Pull request closed without merging**
