### PR TITLE
Fix 1 typo

### PR DESCRIPTION
**Pull request by mQkatz**
To try out Postman community collaboration, made digstible more digestible. Thanks for pointing me to this style guide!

### CODE REVIEW

**Comment by SueSmith** [comment]
Hi Michael!! 👋 Thanks so much for fixing this typo / indigestion.. 🤦‍♀️ Would you mind removing the change to package-lock json file from the pr so that it's just the change to the .md file? 

I must remember to add that to the contribution guide, it tends only to happen when you've recently set up the repo locally.. on that note thanks for taking the time to get the site running on your local machine! 🚀

**Comment by mQkatz** [comment]
Hi again @SueSmith: Sure, but what's your protocol for backing out one file? (Apologies, I _knew_ this was a junk file delta, but foolishly added both files on the same commit.) 🤦

**Comment by SueSmith** [comment]
Oh lol yeah good question, it can get messy once it's committed, I would try updating your local branch from develop branch then pushing again. If that doesn't work you should be able to revert the commit locally e.g. in github desktop (which I use out of sheer laziness) from history, although since it's all one commit that would mean making your edit again.. 🙃

**Comment by mQkatz** [comment]
Went commando (too lazy to install a graphical Git client on this personal machine!). If the result looks dodgy, can close this PR and reopen a clean one. Thanks.

**Comment by SueSmith** [comment]
So I reverted a couple things (then realised I had to revert one of the reverts 🙃) and we are finally down to the one file change - the things we do to please git.. 😂 

Anyway we should be good to go now - thanks again @mQkatz!

**Comment by mQkatz** [comment]
@SueSmith Thanks for your help getting this through! I suspect we're all just part of an elaborate simulation to please git...and the rare quadruple negative is prized by all writers.

**Comment by SueSmith** [comment]
A pleasure! I need to figure out a workflow to help us avoid this one.. 😬

**Comment by mQkatz** [comment]
🤦 I should have just `git checkout -- package-lock json`, then pushed that as a 2nd commit. (Not avoidance, but probably the cleanest workaround?)

**Comment by SueSmith** [comment]
Yeah that sounds like probably the recommended way to fix it but I can't help feeling we should be able to avoid it and make the whole process easier for people.. 🤔

**Pull request merged**
