### PR TITLE
Fix Enable Profile image link

### PR DESCRIPTION
**Pull request by KKVANONYMOUS**
Fixes: #2770 

This PR fixes the broken Enable Profile image link specified in the issue.
Please review it and suggest the changes required

### CODE REVIEW

**Comment by ch264** [comment]
Hey @KKVANONYMOUS Thanks so much for working on this 🚀 

@claireriley can you confirm if this is the correct image please? 

Screen Shot 2021-01-05 at 2 49 23 PM

**Comment by claireriley** [comment]
@jerry-li-dev please review!

**Review by jerry-li-dev — APPROVED** [review]
Yes, this is the correct image to fix the image link in the doc.

**Comment by jerry-li-dev** [comment]
@KKVANONYMOUS This looks ready to merge.

**Comment by KKVANONYMOUS** [comment]
@claireriley @ch264 Please review and merge it.

**Pull request merged**
