### PR TITLE
404 image #2357

### PR DESCRIPTION
**Pull request by HarshaVardhan16**

### CODE REVIEW

**Comment by SueSmith** [comment]
I think this pr might have some unintended file changes in it..? The 404 image issue is actually already being addressed in any case. If you don't mind holding off for now we'll work through one pr / issue at a time - let's figure out the redirects one first and take it from there, thanks again!

**Comment by HarshaVardhan16** [comment]
@SueSmith sorry for the back to back pull requests. Take your time and provide me with some feedback. I have recently started to contribute.

**Comment by SueSmith** [comment]
No apologies necessary! Your contributions are much appreciated! 🙌 If you can bear with us we'll work through them one at a time. 🙂

**Comment by SueSmith** [comment]
Hi @HarshaVardhan16 I'll close this pr because we have fixes merged now, thank you again for contributing and please feel free to pick up others! 🙂

**Pull request closed without merging**
