### PR TITLE
Markeng 1509 update searchPreview to use styled components

### PR DESCRIPTION
**Pull request by OlliesWorld**
-delete .scss
-update searchPreview.jsx to use styled components and export style
-import styled component to Dropdown.jsx

### CODE REVIEW

**Review by ch264 — CHANGES_REQUESTED** [review]
The Hits display with a marker and styled as a link
Screen Shot 2022-08-04 at 1 34 09 PM

**Comment by OlliesWorld** [comment]
fixed the pagination nav and added wrap for mobile.

**Comment by OlliesWorld** [comment]
took out pagination wrap and fixed duplicate styles

**Review by ch264 — APPROVED** [review]
Pulled, build, ran, LGTM 🍻

**Pull request merged**
