### PR TITLE
Updated download links for v7

### PR DESCRIPTION
**Pull request by kamalaknn**

### CODE REVIEW

**Comment by kamalaknn** [comment]
Postman v7 is no longer the latest version. So [this page](https://learning.postman.com/docs/administration/upgrading-to-v8/#downloading-postman-v7-app) should use special links to download v7 apps instead of pointing to latest links. We've also dropped support for 32 bit linux packages.

**Review by numaanashraf — APPROVED** [review]

**Comment by numaanashraf** [comment]
@sowmyaraj92 Review please 🙏

**Review by sowmyaraj92 — APPROVED** [review]
@kamalaknn This looks great! 🎉

**Comment by sowmyaraj92** [comment]
> Postman v7 is no longer the latest version. So [this page](https://learning.postman.com/docs/administration/upgrading-to-v8/#downloading-postman-v7-app) should use special links to download v7 apps instead of pointing to latest links. We've also dropped support for 32 bit linux packages.

@kamalaknn Thank you for pointing this out. We are good to merge the changes!👍

**Pull request merged**
