### PR TITLE
Add documentation for use with other Chromium flavours

### PR DESCRIPTION
**Pull request by l3nn4rt**

### CODE REVIEW

**Comment by SueSmith** [comment]
Thank you so much for the PR @l3nn4rt and apologies for the delay in responding 😅 I wonder if @claireriley could maybe check this one out since I am clueless about this part of Postman 🙃

**Comment by claireriley** [comment]
Hey @l3nn4rt ! We'll test these steps and get back to you.

**Comment by jkonrath-postman** [comment]
Note to self: this file moved to postman-docs/src/pages/docs/sending-requests/capturing-request-data/interceptor.md and has changed since, so this will likely take a new PR. I'm taking a look.

**Comment by jkonrath-postman** [comment]
Hi @l3nn4rt thanks for the contribution and sorry about the wait. I couldn't cleanly merge this because our site layout has shifted, so I opened another PR at #3123 and I'll add the info there. Thanks again!

**Pull request closed without merging**
