### PR TITLE
Extended the documentation for the second paragraph of README.md

### PR DESCRIPTION
**Pull request by ProgrammingMuffin**
**What Changed?**

Added more information about postman to the second paragraph of _README.md_ file. 

**Why the change?**

This is so that people can have a better idea about what postman is and why they must use it. This reduces the confusion among the developers who are new to this concept of API testing and can have a quick _brief overview of the features_ that are provided to them by Postman

### CODE REVIEW

**Comment by SueSmith** [comment]
@ProgrammingMuffin thanks so much for this! 🏆 The readme could definitely use some attention.. Would you mind changing the "holy grail" language? Just in case it's not familiar to people since we have a global community. Will be delighted to merge this if you can alter that a wee bit.. 😬

**Comment by ProgrammingMuffin** [comment]
Incorporated @SueSmith  suggestions into the changes as seen in commit #04ad39d 👍

**Comment by SueSmith** [comment]
Thanks again @ProgrammingMuffin! 🎉

**Comment by ProgrammingMuffin** [comment]
No problem! My pleasure! @SueSmith

**Pull request merged**
