### PR TITLE
included embedded approved video

### PR DESCRIPTION
**Pull request by tobiaswettstein**
Hello all
I have embedded the new approved video (with help from Christina). The video should be embedded instead of just a link so it is easier to be found and noticed.
Thanks all!
Tobi

### CODE REVIEW

**Comment by ch264** [comment]
@SueSmith @nicktran We can embed the video in the docs with an image of the video. Clicking on the image of the video will open the video in Youtube.

**Comment by SueSmith** [comment]
Hm not sure it's obvious enough visually that this is a video, can we just embed it using html instead so it plays in the page? Pretty sure the docs used to have videos embedded directly..

**Comment by SueSmith** [comment]
For reference this is what it looks like when I run locally:
Screenshot 2020-01-13 at 10 25 00

I would probably put it in a different part of the page too but can sort that once we figure out how it's getting embedded.

**Comment by ch264** [comment]
@SueSmith I will look into how we can embed the video into html. I am not sure if that is at all possible with Markdown. I will get back with more info

**Comment by SueSmith** [comment]
@ch264 I just meant drop it into the markdown page in html directly using the youtube embed code or whatever..

**Comment by ch264** [comment]
@SueSmith, I created a new PR for the issue # 2098

https://github.com/postmanlabs/postman-docs/pull/2103

**Comment by ch264** [comment]
@tobiaswettstein Thanks very much for the PR. We have found a way to embed videos in Markdown with Gatsby plugins. I will therefore close this PR.

**Pull request closed without merging**
