### PR TITLE
[151] added pagination to search results

### PR DESCRIPTION
**Pull request by ch264**

### CODE REVIEW

**Comment by ch264** [comment]
@loopDelicious 🙌

**Comment by ch264** [comment]
Screen Shot 2020-08-14 at 5 28 09 PM
Screen Shot 2020-08-14 at 5 28 15 PM

**Comment by loopDelicious** [comment]
lgtm thanks @ch264 !

**Comment by ch264** [comment]
@loopDelicious In order for me to be able to merge this PR, can you please approve it? Thanks

**Comment by ch264** [comment]
@loopDelicious for security reasons, a comment does not approve a PR and merging is blocked. 

Screen Shot 2020-08-18 at 9 34 18 AM

Please go to `Files changed` and select `Review changes`, select `approve`, add a comment that you approve this,  and then select `submit`. 



Official approval that way will unblock Merging. Thanks

**Pull request merged**
