### PR TITLE
added syntax highlighting

### PR DESCRIPTION
**Pull request by ch264**

### CODE REVIEW

**Comment by ch264** [comment]
Screen Shot 2020-04-15 at 4 52 50 PM

**Comment by SueSmith** [comment]
Thanks so much for doing this @ch264!!! 🎉 🚀 🥳 

Think we could have all of the text in code excerpts monospaced too?

**Comment by ch264** [comment]
@SueSmith yep, I changed the font to monospace

**Comment by ch264** [comment]
Screen Shot 2020-04-16 at 3 45 48 PM

**Comment by SueSmith** [comment]
@ch264 nice!!! It looks great.

There are some places it's rendering not in monospace e.g. the "function", "var", "true", "false", "new", "JSON" in js excerpts - possibly others I'm missing, I _think_ the bits that are rendering purple and the yellowish orange color..?

Screenshot 2020-04-17 at 10 30 14

There is also an issue with the layout e.g. on test script examples page which rings a bell, think we had something similar a while back so am sure you'll know how to fix it..

Screenshot 2020-04-17 at 10 27 03

If you're tweaking it feel free to ping me and I'll try and click through places that are likely to have different types of code in them.. 🙂

**Comment by SueSmith** [comment]
Paging @claireriley - could you give us a wee hand to test this out too? If you check out the branch locally and run an npm install you should hopefully be able to see how it's all rendering.. 🙏

**Comment by ch264** [comment]
@SueSmith 
- the video is targeted by prism, so I have to figure out how we can solve this. 
- the horizontal scroll breaks the page layout. 
- I will look into these specific pages. Not sure why the layout is behaving like this. 
- no problem, I can add a lighter grey.

**Comment by SueSmith** [comment]
@ch264 the only way I can get the pipe character to render reliably (e.g. in [requests](https://learning.postman.com/docs/postman/sending-api-requests/requests/#encoding-your-request-urls)) is using `<code>` tags, would you be able to apply the same highlighting to those? Any alternative suggestions welcome, have googled this so much..

**Comment by claireriley** [comment]
Impact-wise it's definitely way better than what we had. 

@ch264 for the inline code I agree on lighter grey for text (closer to white), the contrast I think would look better. Are there slightly lighter options we could try for the background on these as well? Visually the intensity is a bit distracting for me, and makes reading a bit choppier in sentences where it switches back and forth between variable name snippets and regular writing.

If we could get the horizontal scroll to work that'd be ideal—it seems like this implementation splits up lines a bit differently than our current one:
Screen Shot 2020-04-23 at 7 26 00 PM
vs
Screen Shot 2020-04-23 at 7 25 49 PM

and it comes across as a bit muddier to read.

I also ran through all the pages in the nav and the only page I saw that was obviously broken for Chrome was the one Sue mentioned.

@SueSmith there's some weird spacing issues we may want to fix at some point—check out /docs/postman/scripts/test-examples/#assertion-library-examples vs the one above it (and below even worse). Not sure of the previous reasoning but in these bright colors it stood out. I can fix it sometime when I get bored 😂

**Comment by SueSmith** [comment]
@claireriley oh god that page needs so much work 😭

**Comment by ch264** [comment]
@SueSmith I found a way to fix the display of the youtube videos. Once this branch is good to go to prod, we can add videos with their iframes by copying the iframe code from Youtube. I am still looking into the layout issue of that one page and the other asks.

**Comment by SueSmith** [comment]
Ah great thanks @ch264! 🎬

**Comment by arlemi** [comment]
@ch264 Now that the blog and LC are on the same architecture, will we be able to port that syntax highlighting to the blog? 👀

**Comment by ch264** [comment]
@arlemi yes, the blog and LC have the same tech frameworks but the data sources are different. However, the data coming back from the blog is not standardised and comes back in many different formats that need to be accounted for. Implementation of syntax highlighting is in planning but no release date can be given just yet.

**Comment by ch264** [comment]
@SueSmith, @claireriley, I updated the PR to the new AI and added the following: 

- I adjusted the page with the table: /docs/writing-scripts/script-references/variables-list/
- I added the same line hight to the code blocks as now: /docs/writing-scripts/script-references/test-examples/
- I also changed the inline code color background to a lighter gray and the font color to a darker gray. 

Please let me know if there are any other changes.

**Comment by SueSmith** [comment]
Thanks @ch264! 🙌 

I think this is looking really good. Think we could have a bit more contrast to make the inline code a little clearer to read?

Screenshot 2020-07-10 at 12 13 03

We will need to try and figure out a way to do horizontal scroll but definitely a future enhancement, in the meantime we can tidy up some of the code excerpts which should help..

Curious to hear from @claireriley and @arlemi 📣

**Comment by ch264** [comment]
I made the text darker and added another pixel of padding around the lnline code: 
Screen Shot 2020-07-10 at 10 08 16 AM

**Comment by claireriley** [comment]
Looks awesome @ch264 ! One thing I might change for the in-line code is make the text a tad larger, maybe 1.2em?

**Comment by ch264** [comment]
@claireriley I updated the font-size to 1.2em:

Screen Shot 2020-07-13 at 10 48 43 AM

**Pull request merged**
