### PR TITLE
Update requesting-access-to-collections.md

### PR DESCRIPTION
**Pull request by soumy47**
Removed the href of the "role", showing the error page by clicking on it.

### CODE REVIEW

**Comment by SueSmith** [comment]
Hi @soumy47 thanks for your interest in contrubuting! I'm not seeing an error on clicking these links, could you explain more about what you're seeing when you click them?

**Comment by soumy47** [comment]
@SueSmith Thanks for reviewing my issue. Whenever  I click on the word "role", it shows an error page. 
Please find the attached file.
Screenshot_2020-09-07 Build software better, together

**Comment by SueSmith** [comment]
@soumy47 hm that is odd, it works fine for me, can you confirm this happens when you click the links in this page? https://learning.postman.com/docs/collaborating-in-postman/requesting-access-to-collections/

**Comment by SueSmith** [comment]
Ah just clicked what's happening, you're clicking the links from the github repo and not from the docs site yes? They will only work in the actual learning center.. 😅

**Comment by soumy47** [comment]
No ,there is absolutely no error in this link @SueSmith

**Comment by SueSmith** [comment]
Cool so I think we can close here!

**Pull request closed without merging**
