### PR TITLE
Clarify docs edits and explore listings #2348

### PR DESCRIPTION
**Pull request by fakela**
This PR is to update Clarify docs edits and explore listings

### CODE REVIEW

**Comment by fakela** [comment]
I should have had this chat in the issue conversation before starting out to make edits  :)

After going through the issue again here is a suggestion its quite different from my initial commit 

_To enable the docs and the associated collections available via the Postman API Network and templates you will need to update your [explore.postman.com](https://explore.postman.com) details manually._

**Review by SueSmith — APPROVED** [review]
moved and extended the info a little..

**Comment by SueSmith** [comment]
Thanks again for the PRs @fakela and apologies for taking so long to review.. Plz fill out our [contributor form](https://docs.google.com/forms/d/e/1FAIpQLSfbLAcxl-IOiv3NmgEaWw7FleOaXnIyIoIrY_zn6U4JvjQBGA/viewform?usp=send_form) so we can send you some swag..! 🚀 🎊 🏆

**Comment by fakela** [comment]
Thank you @SueSmith

**Pull request merged**
