### PR TITLE
Publish api spec, monitoring docs, live preview, invalid chars, conflict ui docs

### PR DESCRIPTION
**Pull request by SueSmith**
@ch264 couple of docs updates if that's cool

### CODE REVIEW

**Comment by SueSmith** [comment]
@ch264 I pushed a few more doc updates to develop - live preview, invalid chars, and conflict ui all of which were released today so if you could give this a wee check over so we can get these updated that would be magic 🙌

**Comment by SueSmith** [comment]
@ch264 something weird is going on in the beta site, certain pages are getting stuck in some sort of refresh loop e.g. am seeing it in https://learning.postman-beta.com/docs/administration/billing/ _I think_ esp if I'm not logged into Postman 😱

**Comment by SueSmith** [comment]
It's only happening on certain pages - the billing one above wasn't actually changed in this pr.. 🤔

**Comment by SueSmith** [comment]
Also happening on this page which _was_ updated, having a hard time finding anything they have in common.. https://learning.postman-beta.com/docs/postman/workspaces/conflicts/ runs fine locally

**Comment by SueSmith** [comment]
...and now it seems to have gone back to normal 😬

**Comment by ch264** [comment]
Looking into this now

**Comment by tristandenyer** [comment]
The Network tab seems to stop at the Algolia call and refresh.

**Comment by ch264** [comment]
The issue is most likely with a redirect. we are looking into the migrated Lambda on AWS

**Comment by tristandenyer** [comment]
I noticed that the production site page works fine, no redirects: https://learning.postman.com/docs/administration/billing/

If this is an issue with the Lambda, and Prod works but Beta does not, then is it safe to say that pushing to Prod should not be an issue? The Lambda is not part of the push to beta or prod—it's outside that pipeline. Meaning, if Prod is woring and beta is not, I would guess that pushing to Prod should NOT get corrupted and not exhibit the same behavior. Right @ch264 and @Ryan-McBride ?

**Comment by SueSmith** [comment]
If we are going ahead and merging to master I have one more pr I'd like to get merged to develop first, was holding off in case it messed up the troubleshooting effort here..

**Pull request merged**
