### PR TITLE
chore: update Test with Monitors examples to use new syntax

### PR DESCRIPTION
**Pull request by gavinroderick**
Made a quick change - going for lunch but will probably run a quick check for other similar quick examples after 💃🏻

## Changes
- Updated test-with-monitors documentation to use new test syntax

### CODE REVIEW

**Review by mark-anthony-postman — APPROVED** [review]
LGTM! Tested the new code examples and they worked correctly. Thanks for the contribution!

**Comment by gavinroderick** [comment]
lovely stuff! Didn't get around to checking for other examples, but will keep an eye out for them when I'm using the docs! 

Just to check as not sure from the contrib guidelines - is it you or me that closes/merges this PR? 😅

**Comment by mark-anthony-postman** [comment]
> Just to check as not sure from the contrib guidelines - is it you or me that closes/merges this PR? 😅

Let's let Jon merge this one 😀

**Comment by jkonrath-postman** [comment]
Thanks @gavinroderick - looks great! I'll go ahead and merge.

**Pull request merged**
