### PR TITLE
[MARKENG-1078] Add "Last Modified" date to Doc files

### PR DESCRIPTION
**Pull request by brandonmcastillo**
This feature returns the latest git commit by the most recent author
- Added new field called lastModifiedDate that can be queried and returned n doc.jsx
- Display "Last Modified: YY:MM:DD" on Doc pages
- The "Last Modified" date displays on all MD files via GraphQL query

### CODE REVIEW

**Review by mclausaudio — APPROVED** [review]
LGTM

**Review by jkonrath-postman — CHANGES_REQUESTED** [review]
* Not working for me. It shows "Last Updated: %as"
* Can we move the date to the bottom of each article?
* Can we change it from "Last Updated" to "Last modified" ?

**Review by jkonrath-postman — APPROVED** [review]
OK, works for me now. Might want to get someone to try it on a Windows or Linux machine to 100% make sure that git log command works.

**Review by HeatherStenson — APPROVED** [review]
Looks good! 🍊

**Review by oswish — APPROVED** [review]
LGTM!

**Review by mark-anthony-postman — APPROVED** [review]
Very cool to have the last modified date on each page! My one request is to make the "Last Modified" text visually distinctive from regular body text. For example, make the font a little smaller, and make it either italics or a gray color. Otherwise this is great! 🙂

**Pull request merged**
