### PR TITLE
[TW-1128] Edit custom governance rules

### PR DESCRIPTION
**Pull request by MatthewPinsker-postman**
* Added new section about editing custom governance rules
* Update note about required role to mention the new API Governance Manager role
* Updated other existing instructions to match the new UI changes

### CODE REVIEW

**Review by mark-anthony-postman — APPROVED** [review]
LGTM! 💎 ✨

**Review by claireriley — APPROVED** [review]
LGTM! ⭐

**Review by savageCoder55 — APPROVED** [review]
LGTM

**Review by jkonrath-postman — APPROVED** [review]
LGTM

**Pull request merged**
