### PR TITLE
[TW-597] Doc installed apps for uptime monitors

### PR DESCRIPTION
**Pull request by mark-anthony-postman**
Smallest PR ever! Just need to note that posting uptime monitor results to Slack is now supported for installed apps 🙂

### CODE REVIEW

**Review by MatthewPinsker-postman — APPROVED** [review]
Looks good to me!

**Review by jkonrath-postman — APPROVED** [review]
LGTM!

**Comment by AbhiramH** [comment]
LGTM!

**Review by AbhiramH — APPROVED** [review]

**Comment by mark-anthony-postman** [comment]
Uptime monitor creation has been disabled in production, so this PR is no longer needed

**Pull request closed without merging**
