### PR TITLE
Remove Sync - Getting started page

### PR DESCRIPTION
**Pull request by madebysid**
@loopDelicious

### CODE REVIEW

**Comment by loopDelicious** [comment]
@madebysid any chance we can resolve this with a server-side redirect instead? unless we are confident that there are no active links to this page (from external sources), would prefer not to delete it.

**Comment by fullpoint** [comment]
Good point -

**Comment by madebysid** [comment]
@loopDelicious Can we redirect to `https://www.getpostman.com/docs/postman/launching_postman/syncing`?

**Comment by loopDelicious** [comment]
@madebysid yes, that redirect works for me.

**Pull request closed without merging**
