### PR TITLE
uptick of AM npm package; refactored homepage to latest props

### PR DESCRIPTION
**Pull request by tristandenyer**
* upticked AM npm package to latest, v1.23.8
* updated href --> src props
* updated homepage with `SectionStyles` and `VideoComponent` AM components
* updated test snapshot to pass
* removed `font-feature-settings` from CSS to remove odd zero character

### CODE REVIEW

**Review by OlliesWorld — CHANGES_REQUESTED** [review]
Index page links are not working. Links on doc pages do work.

**Review by ch264 — CHANGES_REQUESTED** [review]
- Footer links are not working
- Edit this doc button is not working
- `Sign up` link on docs page lost styling and is not working
- links on landing page work

**Review by ch264 — APPROVED** [review]
all links are working

**Review by OlliesWorld — APPROVED** [review]
LGTM

**Pull request merged**
