### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by kappy904**
enpdoints => endpoints

### CODE REVIEW

**Comment by ch264** [comment]
Hi @kappy904, Thank you for spotting this typo 🙌 

I can see that your branch has some conflicts. Can you please resolve them and let me know when you updated your branch? 

Thank you 🚀

**Comment by kappy904** [comment]
@ch264 Hi there. I tried merging master into my branch and there are still conflicts. Perhaps I don't have the correct permission? Thank you

**Comment by SueSmith** [comment]
Hi @kappy904! Apologies for the hassle, we actually completely restructured the docs a few days ago which is why this conflict is happening. If you're using GitHub desktop you can try `Branch` > `Update from develop` (develop is our default branch rather than master), then choose how to resolve the conflicts - you'll need to choose the moved file from the new structure. In all honesty for this change it might be easier to just fix the typo over again lol 🙈 this is the new location of the file https://github.com/postmanlabs/postman-docs/blob/develop/src/pages/docs/getting-started/sending-the-first-request.md

**Comment by SueSmith** [comment]
We've actually had this fixed in another PR - thanks so much anyway @kappy904!

**Pull request closed without merging**
