### PR TITLE
Adjust cards to add Postman Space Camp on Learning Center Home page

### PR DESCRIPTION
**Pull request by meenakshi-dhanani**
card-changes-lc

@loopDelicious can you review this change once?

### CODE REVIEW

**Comment by meenakshi-dhanani** [comment]
It's a little up and down the CTAs, because all other descriptions are 2 lines in the 6-block and one line in the 3 block. @loopDelicious I'm thinking we modify Postman Space Camp to say - Keep an eye out for upcoming educational webinars. and the community block to say - Connect to the Postman community.

Would that be okay?

**Review by loopDelicious — CHANGES_REQUESTED** [review]
I ❤️ the gif for the laziest reviewer @meenakshi-dhanani . I agree with your suggestion, can we update the copy to 

See Webinars - See previous and upcoming educational webinars. ("educational" can be trimmed if needed)
Visit Forum - Join the Postman community.

**Comment by meenakshi-dhanani** [comment]
> I ❤️ the gif for the laziest reviewer @meenakshi-dhanani . I agree with your suggestion, can we update the copy to
> 
> See Webinars - See previous and upcoming educational webinars. ("educational" can be trimmed if needed)
> Visit Forum - Join the Postman community.

Updated it now 

card-changes-lc

**Review by loopDelicious — APPROVED** [review]
lgtm! thank you @meenakshi-dhanani

**Review by jkonrath-postman — APPROVED** [review]
If @loopDelicious is happy, I'm happy. Approved!

**Pull request merged**
