### PR TITLE
Add article:published_time meta tag to <head>, extending established patterns

### PR DESCRIPTION
**Pull request by cjbt**
https://github.com/postmanlabs/postman-docs/issues/3940
- prints `<meta property="article:published_time" content="2022-03-14T15:00:00+00:00">` in `<head>` on build—for every page
- and the date in content matches the date at the bottom of the page we are verifying.

### CODE REVIEW

**Comment by tristandenyer** [comment]
Thank you @cjbt . I pulled and ran this locally, but not seeing the `<meta property="article:published_time"` being printed in the head.
Screenshot 2023-05-24 at 16 28 55

**Comment by cjbt** [comment]
> Thank you @cjbt . I pulled and ran this locally, but not seeing the `<meta property="article:published_time"` being printed in the head. Screenshot 2023-05-24 at 16 28 55

Thanks for getting back to me. Let me dig into this

**Comment by cjbt** [comment]
@tristandenyer I'm able to see it on my side. Sometimes it's at the bottom of the `<Head>` list

Screenshot 2023-05-31 at 11 13 20 PM

**Comment by cjbt** [comment]
closing this because it's stale

**Pull request closed without merging**
