### PR TITLE
TW 830 Update the "create team" section

### PR DESCRIPTION
**Pull request by HeatherStenson**
This PR updates https://learning.postman.com/docs/collaborating-in-postman/working-with-your-team/collaboration-overview/#creating-a-team to account for the limited roll-out of multi-team.

### CODE REVIEW

**Review by claireriley — APPROVED** [review]
LGTM! ⭐

**Comment by Postmanaut-Adrian** [comment]
Hey @HeatherStenson , 

The changes look fantastic and will address the confusion we are encountering with some users!  

Can we replace “You can also create another team. To create another team…” with “You can create additional teams. To create a new team….”? As the current phrase may give the perception that only one team can be created.

Thank you so much for putting this together!

**Comment by HeatherStenson** [comment]
Thank you for reviewing @Postmanaut-Adrian! Updated per your comments 💪

**Comment by Raj-postman** [comment]
@HeatherStenson Since we are adding the multi-team details on the doc now, can we also include the below section which may help users look into it to avoid any confusion? Reword the statement if required, please.

```Once you are part of a multi-team, all the data and workspaces (including personal) become associated with the team. This means when you leave the team or are removed from the team, all of the data remains with the team and you wouldn't have access to the same.```

**Comment by HeatherStenson** [comment]
Thanks for the suggestion @Raj-postman, tagging you in a new Jira for that update.

**Pull request merged**
