### PR TITLE
Push API Builder, inline edit, monitoring, API dev / sync content updates to prod

### PR DESCRIPTION
**Pull request by SueSmith**

### CODE REVIEW

**Comment by SueSmith** [comment]
@ch264 something going wrong with aws and algolia key environment check 😬

**Comment by ch264** [comment]
@SueSmith ok I will check that the keys are still the right ones

**Comment by ch264** [comment]
@SueSmith Checks passed again.

**Comment by SueSmith** [comment]
Thanks @ch264!

**Pull request merged**
