### PR TITLE
Updating Activity Feed to Changelog

### PR DESCRIPTION
**Pull request by ArifPMan**

### CODE REVIEW

**Comment by DannyDainton** [comment]
@tristandenyer was your change just to do the headings? We'll still need to change all the activity feed references to Changelog right?

**Comment by ArifPMan** [comment]
@tristandenyer @DannyDainton I will do all those content changes and will update this PR.

**Comment by kaustavdm** [comment]
@ArifPMan Reminder that these changes are pending. This PR has been open for long now. Please take a stab at it whenever you find time.

**Comment by kaustavdm** [comment]
Closing this PR as this is conflict ridden and quite stale. We will redo this section as part of ongoing initiatives to fix docs gaps.

**Pull request closed without merging**
