### PR TITLE
updated secondary button styles

### LINKED ISSUE #2195: Update secondary button syles
The Secondary button styles have changed. The corners are now using the same corners as the Primary buttons.
Current:
Screen Shot 2020-02-21 at 9 17 14 AM

New:
Screen Shot 2020-02-21 at 9 26 37 AM

Be sure they share the same CSS so as to not duplicate styling.

### PR DESCRIPTION
**Pull request by sergeycw**
Fixes #2195

### CODE REVIEW

**Comment by sergeycw** [comment]
> Hey @sergeycw, thanks for contributing. The border-radius on &.btn__secondary-light should be changed to 3px to match the primary button.
> 
> Thanks so much.

hi @ch264! thanks for the comment. Did it.

**Comment by ch264** [comment]
Hey @sergeycw, thanks for contributing. I can see that the border-radius was deleted in the updated PR for the secondary-light and secondary-dark buttons.
 
The button with the class '&.btn__secondary-light' needs a border-radius of 3px to match the primary button's border radius. Both buttons should have the same border-radius. 

Thank you and have a great day

**Comment by ch264** [comment]
Hey @sergeycw, thanks for contributing. I can see that the border-radius was deleted in the updated PR for the secondary-light and secondary-dark buttons.
 
The button with the class '&.btn__secondary-light' needs a border-radius of 3px to match the primary button's border radius. Both buttons should have the same border-radius. 

Thank you and have a great day

**Comment by sergeycw** [comment]
@ch264 currently we have one common .btn class with border-radius 3px  that affects all buttons (primary and secondary). so we don't need to specify each class separately. but maybe I misunderstood something.

thanks!

**Comment by ch264** [comment]
Hey @sergeycw, thanks so much for your time and contribution. We have accepted a PR that solves this ticket according to spec. Thanks again and please feel free to contribute to any of our other tickets.

**Pull request closed without merging**
