### PR TITLE
[TW-893] Fix custom domain screenshots

### PR DESCRIPTION
**Pull request by mark-anthony-postman**
Removed beta reference from two screenshots

### CODE REVIEW

**Review by petewitcher — APPROVED** [review]
LGTM!

**Review by jkonrath-postman — APPROVED** [review]
LGTM

**Review by Raj-postman — CHANGES_REQUESTED** [review]
@mark-anthony-postman The image here still appears to be the one from Beta, can we rectify this if possible?
https://assets.postman.com/postman-docs/v10/custom-domains-dns-records-v10-9.jpg

Beta

**Comment by mark-anthony-postman** [comment]
> @mark-anthony-postman The image here still appears to be the one from Beta, can we rectify this if possible?
> 

@Raj-postman  Thanks for catching the additional beta references. I updated the screenshot again. Hopefully that's the last of them! 😅

**Review by Raj-postman — APPROVED** [review]
This looks all good now :)

**Pull request merged**
