### PR TITLE
Integrations/available integrations

### PR DESCRIPTION
**Pull request by taehoshino**
I made updates to integrations pages. Main changes are:
- Updated URL link: Integrations page is no longer located in https://go.postman.co/workspaces.
- Individual integration page no longer has "View Details" or "Configured Integrations" tab.
- Uploading updated screenshots below. 

bitbucket-postman-page
aws-api-gateway-integration-page
integrations_APImatic
WS-integrations-msTeam
WS-integration-msTeams-monRun

### CODE REVIEW

**Comment by taehoshino** [comment]
integrations_dropbox1
add-integration-datadog
integrations_datadog2
coralogix_viewdetails3
coralogix_viewdetails

**Comment by SabriH10** [comment]
@claireriley Hi Claire, just a ping here, as it seems https://learning.postman.com/docs/integrations/available-integrations/github/#configuring-github-integration-for-collections still mentions the following:
`In the Integrations tab for your workspace, select Github from the list of third party Integrations.` Which seems to be outdated.

**Comment by claireriley** [comment]
Hey @SabriH10 thanks for pinging a reminder and @taehoshino for doing this! @jerry-li-dev can you please check this out when you have a chance and resolve the conflicts?

**Review by jkonrath-postman — APPROVED** [review]
Reviewed, looks good.
I merged, but there were a few where we had newer changes that already fixed the issue.

**Pull request merged**
