### PR TITLE
Correct typo in The API Wokflow docs

### PR DESCRIPTION
**Pull request by louisfisch**
Fix the issue #2349

### CODE REVIEW

**Comment by SueSmith** [comment]
That was quick! Thanks so much @louisfisch 🎉 🚀 🏆

**Comment by SueSmith** [comment]
Not sure why the check is failing but looks like an issue on our end so we'll get it sorted..

**Comment by SueSmith** [comment]
Also something weird is happening with my notifications, getting them in the wrong order lol, GitHub having a few issues I think 🙈

**Comment by louisfisch** [comment]
You're welcome. I think it's on the GitHub's end though https://www.githubstatus.com/incidents/2y6v4ltq26g7

**Comment by SueSmith** [comment]
Ah great thanks hadn't seen this. Will try again later!

**Comment by louisfisch** [comment]
Is there something I can do so the build can pass? I don't fully understand why it is failing. I thought it was due to the GitHub incident but it keeps failing even though the incident was resolved.

**Comment by SueSmith** [comment]
@louisfisch hm I was wondering why it's still failing too, other prs are now passing.. anyway it shouldn't be on your end, you've literally changed one line of text..

Paging @ch264 who I believe set these checks up and am hoping has more of a clue than me into what they actually do.. 😬

**Comment by ch264** [comment]
@louisfisch Thanks so much for contributing 🚀 I have not experienced this error message before. This might be a rebase or clone issue resulting in an issue with GitHub where is does not recognize the commit.

I would probably recommend to create a new branch and create a new pull request with the fix (possibly cloning down the repo again and start afresh)? Sorry, I will research some more into this issue so for I would recommend a fresh start for the PR 😄

**Comment by SueSmith** [comment]
@louisfisch commited a daft little change to your pr to see if that somehow bypassed the weirdness and it seems to have worked lol 🙃

**Pull request merged**
