### PR TITLE
Dark mode implemented

### PR DESCRIPTION
**Pull request by tanishq-mishra**

### CODE REVIEW

**Comment by tanishq-mishra** [comment]
Can somebody help me with this? I don't get it, why does it say "all checks have failed"? It is running for me locally. I'm sorry if this is stupid, I'm new to this.

**Comment by SueSmith** [comment]
Thanks for the PR! Plz bear with us while our eng team has a look (likely next week at the earliest..)

**Comment by ch264** [comment]
Hi @tanishq-mishra, this is great. Thank you for contributing 🙌 
Design changes have to be approved by our design team. 

In the meanwhile, you can see in the tab 'checks' the stage at which the check failed. I can see that you PR did not pass Unit testing. This is most likely due to the changes and the snapshots in our Jest not matching with the predefined ones. 

If design approves the dark mode, I can help you pass your PR. Thanks again for all you hard work, this is awesome. 🚀

**Comment by tanishq-mishra** [comment]
Thank you so much @ch264 , this is my first ever contribution to an open source project.

**Comment by jkonrath-postman** [comment]
Hi @tanishq-mishra thanks for your work on this, and sorry for the delay in this reply.

We've decided not to merge this PR because this is a feature that would be up to our design team to implement. They continually make changes to the site, so I will suggest this to them.

Thanks again though for the contribution, and please feel free to contribute to our documentation.

**Pull request closed without merging**
