### PR TITLE
Update the Postman Echo link for the Sending your first request doc

### PR DESCRIPTION
**Pull request by gitThingsDone**

### CODE REVIEW

**Comment by gitThingsDone** [comment]
@SueSmith this change is in response to https://github.com/postmanlabs/postman-docs/issues/2812, could you please help review this PR

**Review by SueSmith — APPROVED** [review]
lgtm

**Comment by tristandenyer** [comment]
@gitThingsDone There are 3 additional places this old URL is listed in the docs. Can you update your PR to cover those too?
Screen Shot 2021-01-26 at 9 06 41 AM

**Comment by gitThingsDone** [comment]
@tristandenyer updated the other files, could you please help review and merge this

**Review by tristandenyer — APPROVED** [review]
LGTM

**Pull request merged**
