### PR TITLE
Added public workspace resource to LC sidebar

### PR DESCRIPTION
**Pull request by Samridhi-98**
**Fixes** #3347 

**Description**

Added following links :
- [x] Postman API
- [x] Postman Public Workspace
- [x] 30 days of Postman for developers
- [x] Postman Answers
- [x] More Visualizer Examples
- [x] Test examples in Postman
- [x] Postman Security Workspace
- [x] Postman API Monitoring Examples 
- [x] Postman Loves Slack - webhooks?
- [x] Postman Collaboration
- [x] Public GraphQL APIs
- [x] Public SOAP APIs
- [x] GraphQL examples
- [x] Sample Visualizations

**Todo :**   `Couldn't able to figure out where to place the following links:`

- [ ] Support Workspace
- [ ] Unbreakable API - negative testing - monitors
- [ ] Fakerjs example
- [ ] Public REST APIs

### CODE REVIEW

**Comment by Samridhi-98** [comment]
@claireriley  Please review my PR.

**Review by jkonrath-postman — CHANGES_REQUESTED** [review]
Can you remove the changes to package-lock.json? This is going to cause conflicts.

**Comment by claireriley** [comment]
Thanks @Samridhi-98 ! I'll take it from here 🙂

**Comment by claireriley** [comment]
@Samridhi-98 closing this PR as I've added your main commit to #3819

**Pull request closed without merging**
