### PR TITLE
Feature/intro rip

### PR DESCRIPTION
**Pull request by JJGothard**
Hi @SueSmith ! What a journey this has been, eh? 😂🤪🙀

- The intro to the RIP button page is up-to-date with the last round of review comments 
- Documenting your API & Sharing collections were updated w/ url to intro page, and those links were tested to make sure they work
- Security considerations & Using the RIP button pages were deprecated; contents added here
- All contextual links look good on my local LC (I think that was the final concern with this page) and the links have been checked and are working
- The redirects page on my machine already had the redirect links and I see that they're in the redirects file in the repo too (prolly from the new Creating a RIP button page)

Also, per our Slack convo, I resaved the file a couple times (the hyphens weren't changing the URL in the local LC, and I wanted to makes sure links would work) and deleted duplicates on my machine. 

Thanks!!!

### CODE REVIEW

**Comment by SueSmith** [comment]
Hey @JJGothard couple things at first glance, there are two file changes missing based on the previous version of this - the redirects and one of the page deletions. If you can sort that out I'll have a proper look through tomorrow.. 🙃

**Comment by JJGothard** [comment]
@SueSmith , the redirects page already has all of the redirects in it (the one that's currently in the repo). I did copy what was on the redirect file from the PR we're planning on deprecating to paste it into the redirect on my local machine, and all the of them were there. 
The collections-run-button file is the one not deprecated here. I believe that was deprecated as part of the new Creating an RIP button page (the contents were moved to that new page). Should I still deprecate here? That pull request isn't in the open PRs anymore, but the contents are also not in prod, so I can't be sure. Thanks!

**Comment by SueSmith** [comment]
@JJGothard Whenever a pr deletes pages it needs to include the redirects for those pages, the redirects that were in the previous version of this pr (which is still open btw https://github.com/postmanlabs/postman-docs/pull/2249/files) are definitely not here - you'll also need to update some of the existing redirects so that they aren't redirecting "to" pages you're deleting as part of this new pr.

The `collections-run-button` page is still in develop branch and has not been deleted yet - it was being deleted in the previous version of this pr as you can see in the files changed tab for the pr link I've included ^^

**Comment by JJGothard** [comment]
@SueSmith , Should be good to go here 👍Thanks!

**Comment by SueSmith** [comment]
@JJGothard the existing redirects affected by these deletions still need updated, for example if another redirect is pointing to a page this pr deletes, that redirect should be updated to point to the new page (so that people are not getting multiple redirects for a single page).

**Comment by JJGothard** [comment]
@SueSmith , If I understood you correctly, I need to go through the redirects and looks for all redirects that point to those deprecated pages and update with the new page that they should direct you to, yes? I've done that, but let me know 😌

**Pull request merged**
