### PR TITLE
Update descriptions and links for cards on Learning center home

### PR DESCRIPTION
**Pull request by meenakshi-dhanani**
- Modified the admin card and replaced the content with the 30 days of Postman challenge
- Updated the description for the Postman Network card

lc-home-update

### CODE REVIEW

**Comment by meenakshi-dhanani** [comment]
@loopDelicious does this look good?

**Review by jkonrath-postman — COMMENTED** [review]
Looks technically correct, but I didn't know we were changing the cards or what the impact is of removing the administer card. @loopDelicious can you confirm?

**Comment by loopDelicious** [comment]
@jkonrath-postman the Test and Admin slots of the 6-block was designed to be refreshed with content relevant to various personas. We're swapping out Admin content for Dev content. We look at WoW traffic for LC home page updates to measure impact. Related efforts, we will be working with Design to add a section with public workspaces to the LC home page.

**Comment by meenakshi-dhanani** [comment]
@jkonrath-postman are we good to go ahead?

**Review by jkonrath-postman — APPROVED** [review]
Looks good @meenakshi-dhanani - go ahead and merge

**Pull request merged**
